fields:
- name: id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: dag_id
  type: STRING
  mode: NULLABLE
  description: null
- name: end_date
  type: TIMESTAMP
  mode: NULLABLE
  description: null
- name: executor_class
  type: STRING
  mode: NULLABLE
  description: null
- name: hostname
  type: STRING
  mode: NULLABLE
  description: null
- name: job_type
  type: STRING
  mode: NULLABLE
  description: null
- name: latest_heartbeat
  type: TIMESTAMP
  mode: NULLABLE
  description: null
- name: start_date
  type: TIMESTAMP
  mode: NULLABLE
  description: null
- name: state
  type: STRING
  mode: NULLABLE
  description: null
- name: unixname
  type: STRING
  mode: NULLABLE
  description: null
