fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: form_factor
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: adm_request_sum
  type: INTEGER
  mode: NULLABLE
- name: adm_empty_response_sum
  type: INTEGER
  mode: NULLABLE
- name: adm_response_tiles_min
  type: INTEGER
  mode: NULLABLE
- name: adm_response_rate
  type: FLOAT
  mode: NULLABLE
