fields:
- name: hour
  type: TIMESTAMP
  mode: NULLABLE
- name: document_namespace
  type: STRING
  mode: NULLABLE
- name: document_type
  type: STRING
  mode: NULLABLE
- name: document_version
  type: STRING
  mode: NULLABLE
- name: error_type
  type: STRING
  mode: NULLABLE
- name: ping_count
  type: INTEGER
  mode: NULLABLE
- name: error_count
  type: INTEGER
  mode: NULLABLE
- name: error_message
  type: STRING
  mode: NULLABLE
- name: sample_payload
  type: STRING
  mode: NULLABLE
- name: error_ratio
  type: FLOAT
  mode: NULLABLE
