fields:
- name: date_day
  type: DATE
  mode: NULLABLE
  description: 'Date of the report.

    '
- name: organization_id
  type: INTEGER
  mode: NULLABLE
  description: 'Organization ID associated with this record.

    '
- name: organization_name
  type: STRING
  mode: NULLABLE
  description: 'Organization name associated with this record.

    '
- name: campaign_id
  type: INTEGER
  mode: NULLABLE
  description: 'Campaign ID associated with this record.

    '
- name: campaign_name
  type: STRING
  mode: NULLABLE
  description: 'Campaign name associated with this record.

    '
- name: ad_group_id
  type: INTEGER
  mode: NULLABLE
  description: 'Ad group ID associated with this record.

    '
- name: ad_group_name
  type: STRING
  mode: NULLABLE
  description: 'Ad group name associated with this record.

    '
- name: keyword_id
  type: INTEGER
  mode: NULLABLE
  description: 'Creative set name associatd with this record.

    '
- name: keyword_text
  type: STRING
  mode: NULLABLE
  description: 'Creative set ID associated with this record.

    '
- name: match_type
  type: STRING
  mode: NULLABLE
  description: 'Controls how ads are matched to user searches; EXACT or BROAD.

    '
- name: currency
  type: STRING
  mode: NULLABLE
  description: 'This currency value should match the respective organization''s currency
    value.

    '
- name: keyword_status
  type: STRING
  mode: NULLABLE
  description: 'The status of the keyword associated with this record.

    '
- name: taps
  type: INTEGER
  mode: NULLABLE
  description: 'Number of taps on keyword on given day.

    '
- name: new_downloads
  type: INTEGER
  mode: NULLABLE
  description: 'App downloads from new users who have never before installed app of
    keyword in a given day.

    '
- name: redownloads
  type: INTEGER
  mode: NULLABLE
  description: 'Number of user downloads where user deletes app and downloads the
    same app again following

    a tap on an ad on the App Store, or downloads the same app to an additional device
    of keyword in a given day.

    '
- name: total_downloads
  type: INTEGER
  mode: NULLABLE
  description: 'The sum of new_downloads and redownloads.

    '
- name: impressions
  type: INTEGER
  mode: NULLABLE
  description: 'The number of impressions of keyword in a given day.

    '
- name: spend
  type: BIGNUMERIC
  mode: NULLABLE
  description: 'The spend on keyword in the given day.

    '
