fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: addon_id
  type: STRING
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: most_common_default_search_engine
  type: STRING
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: is_system
  type: BOOLEAN
  mode: NULLABLE
- name: active_hours_sum
  type: FLOAT
  mode: NULLABLE
- name: total_uri_count_sum
  type: INTEGER
  mode: NULLABLE
- name: tab_open_event_count_sum
  type: INTEGER
  mode: NULLABLE
- name: devtools_toolbox_opened_count_sum
  type: INTEGER
  mode: NULLABLE
- name: sap_searches
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
- name: tagged_sap_searches
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
- name: tagged_follow_on_searches
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
- name: organic_searches
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
- name: searches_with_ads
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
- name: ad_clicks
  type: RECORD
  mode: NULLABLE
  fields:
  - name: google
    type: INTEGER
    mode: NULLABLE
  - name: bing
    type: INTEGER
    mode: NULLABLE
  - name: ddg
    type: INTEGER
    mode: NULLABLE
  - name: amazon
    type: INTEGER
    mode: NULLABLE
  - name: yandex
    type: INTEGER
    mode: NULLABLE
  - name: other
    type: INTEGER
    mode: NULLABLE
  - name: total
    type: INTEGER
    mode: NULLABLE
