fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: nvda
  type: INTEGER
  mode: NULLABLE
- name: jaws
  type: INTEGER
  mode: NULLABLE
- name: oldjaws
  type: INTEGER
  mode: NULLABLE
- name: we
  type: INTEGER
  mode: NULLABLE
- name: dolphin
  type: INTEGER
  mode: NULLABLE
- name: serotek
  type: INTEGER
  mode: NULLABLE
- name: cobra
  type: INTEGER
  mode: NULLABLE
- name: zoomtext
  type: INTEGER
  mode: NULLABLE
- name: kazaguru
  type: INTEGER
  mode: NULLABLE
- name: youdao
  type: INTEGER
  mode: NULLABLE
- name: unknown
  type: INTEGER
  mode: NULLABLE
- name: uiautomation
  type: INTEGER
  mode: NULLABLE
- name: visperoshared
  type: INTEGER
  mode: NULLABLE
- name: magnifier
  type: INTEGER
  mode: NULLABLE
- name: narrator
  type: INTEGER
  mode: NULLABLE
- name: on_screen_keyboard
  type: INTEGER
  mode: NULLABLE
- name: speech_recognition
  type: INTEGER
  mode: NULLABLE
- name: touch_keyboard_and_handwriting_panel
  type: INTEGER
  mode: NULLABLE
- name: voice_over
  type: INTEGER
  mode: NULLABLE
- name: other
  type: INTEGER
  mode: NULLABLE
