fields:
- name: date_day
  type: DATE
  mode: NULLABLE
- name: campaign_id
  type: INTEGER
  mode: NULLABLE
- name: campaign_name
  type: STRING
  mode: NULLABLE
- name: currency
  type: STRING
  mode: NULLABLE
- name: taps
  type: INTEGER
  mode: NULLABLE
- name: new_downloads
  type: INTEGER
  mode: NULLABLE
- name: redownloads
  type: INTEGER
  mode: NULLABLE
- name: total_downloads
  type: INTEGER
  mode: NULLABLE
- name: impressions
  type: INTEGER
  mode: NULLABLE
- name: campaign_spend
  type: BIGNUMERIC
  mode: NULLABLE
- name: clients_activated
  type: INTEGER
  mode: NULLABLE
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
- name: campaign_spend_per_activation
  type: BIGNUMERIC
  mode: NULLABLE
