fields:
- name: dag_id
  type: STRING
  mode: NULLABLE
  description: Airflow DAG id
- name: run_type
  type: STRING
  mode: NULLABLE
  description: manual, scheduled or backfill
- name: external_trigger
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if the DAG was triggered externally
- name: state
  type: STRING
  mode: NULLABLE
  description: State of the DAG run instance (e.g. success)
- name: execution_date
  type: TIMESTAMP
  mode: NULLABLE
  description: Execution date of the DAG Run instance
- name: start_date
  type: TIMESTAMP
  mode: NULLABLE
  description: When the DAG run started
- name: end_date
  type: TIMESTAMP
  mode: NULLABLE
  description: When the DAG run finished
