fields:
- name: build_number
  type: INTEGER
  mode: NULLABLE
  description: null
- name: category
  type: STRING
  mode: NULLABLE
  description: null
- name: date
  type: DATE
  mode: NULLABLE
  description: null
- name: description
  type: STRING
  mode: NULLABLE
  description: null
- name: is_security_driven
  type: BOOLEAN
  mode: NULLABLE
  description: null
- name: product
  type: STRING
  mode: NULLABLE
  description: null
- name: version
  type: STRING
  mode: NULLABLE
  description: null
- name: major_version
  type: NUMERIC
  mode: NULLABLE
- name: minor_version
  type: NUMERIC
  mode: NULLABLE
- name: patch_version
  type: NUMERIC
  mode: NULLABLE
- name: beta_version
  type: NUMERIC
  mode: NULLABLE
