fields:
- name: date
  type: DATE
  mode: NULLABLE
- name: logName
  type: STRING
  mode: NULLABLE
- name: resource
  type: RECORD
  mode: NULLABLE
  fields:
  - name: type
    type: STRING
    mode: NULLABLE
  - name: labels
    type: RECORD
    mode: NULLABLE
    fields:
    - name: instance_id
      type: STRING
      mode: NULLABLE
    - name: zone
      type: STRING
      mode: NULLABLE
    - name: project_id
      type: STRING
      mode: NULLABLE
    - name: cluster_name
      type: STRING
      mode: NULLABLE
    - name: namespace_name
      type: STRING
      mode: NULLABLE
    - name: container_name
      type: STRING
      mode: NULLABLE
    - name: pod_name
      type: STRING
      mode: NULLABLE
    - name: location
      type: STRING
      mode: NULLABLE
- name: textPayload
  type: STRING
  mode: NULLABLE
- name: jsonPayload
  type: RECORD
  mode: NULLABLE
  fields:
  - name: block
    type: BOOLEAN
    mode: NULLABLE
  - name: op
    type: STRING
    mode: NULLABLE
  - name: action
    type: STRING
    mode: NULLABLE
  - name: errno
    type: FLOAT
    mode: NULLABLE
  - name: foundin
    type: FLOAT
    mode: NULLABLE
- name: timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: receiveTimestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: severity
  type: STRING
  mode: NULLABLE
- name: insertId
  type: STRING
  mode: NULLABLE
- name: httpRequest
  type: RECORD
  mode: NULLABLE
  fields:
  - name: requestMethod
    type: STRING
    mode: NULLABLE
  - name: requestUrl
    type: STRING
    mode: NULLABLE
  - name: requestSize
    type: INTEGER
    mode: NULLABLE
  - name: status
    type: INTEGER
    mode: NULLABLE
  - name: responseSize
    type: INTEGER
    mode: NULLABLE
  - name: userAgent
    type: STRING
    mode: NULLABLE
  - name: remoteIp
    type: STRING
    mode: NULLABLE
  - name: serverIp
    type: STRING
    mode: NULLABLE
  - name: referer
    type: STRING
    mode: NULLABLE
  - name: cacheLookup
    type: BOOLEAN
    mode: NULLABLE
  - name: cacheHit
    type: BOOLEAN
    mode: NULLABLE
  - name: cacheValidatedWithOriginServer
    type: BOOLEAN
    mode: NULLABLE
  - name: cacheFillBytes
    type: INTEGER
    mode: NULLABLE
  - name: protocol
    type: STRING
    mode: NULLABLE
- name: labels
  type: RECORD
  mode: NULLABLE
  fields:
  - name: compute_googleapis_com_resource_name
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_deployment
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_app_kubernetes_io_component
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_env_code
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_pod_template_hash
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_app_kubernetes_io_name
    type: STRING
    mode: NULLABLE
  - name: k8s_pod_app_kubernetes_io_instance
    type: STRING
    mode: NULLABLE
- name: operation
  type: RECORD
  mode: NULLABLE
  fields:
  - name: id
    type: STRING
    mode: NULLABLE
  - name: producer
    type: STRING
    mode: NULLABLE
  - name: first
    type: BOOLEAN
    mode: NULLABLE
  - name: last
    type: BOOLEAN
    mode: NULLABLE
- name: trace
  type: STRING
  mode: NULLABLE
- name: spanId
  type: STRING
  mode: NULLABLE
- name: traceSampled
  type: BOOLEAN
  mode: NULLABLE
- name: sourceLocation
  type: RECORD
  mode: NULLABLE
  fields:
  - name: file
    type: STRING
    mode: NULLABLE
  - name: line
    type: INTEGER
    mode: NULLABLE
  - name: function
    type: STRING
    mode: NULLABLE
- name: split
  type: RECORD
  mode: NULLABLE
  fields:
  - name: uid
    type: STRING
    mode: NULLABLE
  - name: index
    type: INTEGER
    mode: NULLABLE
  - name: totalSplits
    type: INTEGER
    mode: NULLABLE
