fields:
- name: submission_minute
  type: TIMESTAMP
  mode: NULLABLE
- name: n_click
  type: INTEGER
  mode: NULLABLE
- name: n_impression
  type: INTEGER
  mode: NULLABLE
- name: n_click_release
  type: INTEGER
  mode: NULLABLE
- name: n_impression_release
  type: INTEGER
  mode: NULLABLE
