fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: placement
  type: STRING
  mode: NULLABLE
- name: partner
  type: STRING
  mode: NULLABLE
- name: version
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: n_engagements
  type: INTEGER
  mode: NULLABLE
- name: interaction
  type: STRING
  mode: NULLABLE
- name: phase
  type: STRING
  mode: NULLABLE
