fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: null
- name: client_id
  type: STRING
  mode: NULLABLE
  description: null
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: application_name
  type: STRING
  mode: NULLABLE
  description: null
- name: build_id
  type: STRING
  mode: NULLABLE
  description: null
- name: channel
  type: STRING
  mode: NULLABLE
  description: null
- name: os
  type: STRING
  mode: NULLABLE
  description: null
- name: os_version
  type: STRING
  mode: NULLABLE
  description: null
- name: country_code
  type: STRING
  mode: NULLABLE
  description: null
- name: main_crash_count
  type: INTEGER
  mode: NULLABLE
- name: content_crash_count
  type: INTEGER
  mode: NULLABLE
- name: gpu_crash_count
  type: INTEGER
  mode: NULLABLE
- name: rdd_crash_count
  type: INTEGER
  mode: NULLABLE
- name: socket_crash_count
  type: INTEGER
  mode: NULLABLE
- name: utility_crash_count
  type: INTEGER
  mode: NULLABLE
- name: vr_crash_count
  type: INTEGER
  mode: NULLABLE
