fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: creation_time
  type: TIMESTAMP
  mode: NULLABLE
- name: dataset
  type: STRING
  mode: NULLABLE
- name: table
  type: STRING
  mode: NULLABLE
- name: cost_usd
  type: FLOAT
  mode: NULLABLE
- name: total_bytes_processed
  type: INTEGER
  mode: NULLABLE
