fields:
- name: submission_date_s3
  type: DATE
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: document_id
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
  - name: date
    type: STRING
    mode: NULLABLE
  - name: geo_country
    type: STRING
    mode: NULLABLE
  - name: geo_city
    type: STRING
    mode: NULLABLE
  - name: app_build_id
    type: STRING
    mode: NULLABLE
  - name: app_name
    type: STRING
    mode: NULLABLE
  - name: app_update_channel
    type: STRING
    mode: NULLABLE
  - name: normalized_channel
    type: STRING
    mode: NULLABLE
- name: application
  type: RECORD
  mode: NULLABLE
  fields:
  - name: architecture
    type: STRING
    mode: NULLABLE
  - name: build_id
    type: STRING
    mode: NULLABLE
  - name: channel
    type: STRING
    mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: platform_version
    type: STRING
    mode: NULLABLE
  - name: version
    type: STRING
    mode: NULLABLE
  - name: display_version
    type: STRING
    mode: NULLABLE
  - name: vendor
    type: STRING
    mode: NULLABLE
  - name: xpcom_abi
    type: STRING
    mode: NULLABLE
- name: creation_date
  type: STRING
  mode: NULLABLE
- name: id
  type: STRING
  mode: NULLABLE
- name: payload
  type: RECORD
  mode: NULLABLE
  fields:
  - name: client
    type: STRING
    mode: NULLABLE
- name: type
  type: STRING
  mode: NULLABLE
- name: version
  type: INTEGER
  mode: NULLABLE
