fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: generated_time
  type: DATETIME
  mode: NULLABLE
- name: user_id
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: seen_in_tier1_country
  type: BOOLEAN
  mode: NULLABLE
