fields:
- name: dag_id
  type: STRING
  mode: NULLABLE
  description: Airflow DAG id
- name: task_id
  type: STRING
  mode: NULLABLE
  description: Airflow task id
- name: run_id
  type: STRING
  mode: NULLABLE
  description: Unique identifier of the task run instance
- name: try_number
  type: INTEGER
  mode: NULLABLE
  description: Attempt number to execute the task
- name: reschedule_date
  type: TIMESTAMP
  mode: NULLABLE
  description: Datetime when task has been rescheduled
- name: start_date
  type: TIMESTAMP
  mode: NULLABLE
  description: When the DAG run started
- name: end_date
  type: TIMESTAMP
  mode: NULLABLE
  description: When the DAG run finished
- name: duration
  type: INTEGER
  mode: NULLABLE
  description: Time elapsed since start until end of task's exeuction (seconds)
