fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: events
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: addon_version
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: subdivision1
  type: STRING
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
