fields:
- name: value
  type: STRING
  mode: NULLABLE
- name: description
  type: STRING
  mode: NULLABLE
- name: dtls_ok
  type: BOOLEAN
  mode: NULLABLE
- name: recommended
  type: BOOLEAN
  mode: NULLABLE
- name: reference
  type: STRING
  mode: NULLABLE
