fields:
- name: asofdate
  type: DATE
  mode: NULLABLE
- name: datasource
  type: STRING
  mode: NULLABLE
- name: date
  type: DATE
  mode: NULLABLE
- name: type
  type: STRING
  mode: NULLABLE
- name: value
  type: FLOAT
  mode: NULLABLE
- name: low90
  type: FLOAT
  mode: NULLABLE
- name: high90
  type: FLOAT
  mode: NULLABLE
- name: p10
  type: FLOAT
  mode: NULLABLE
- name: p20
  type: FLOAT
  mode: NULLABLE
- name: p30
  type: FLOAT
  mode: NULLABLE
- name: p40
  type: FLOAT
  mode: NULLABLE
- name: p50
  type: FLOAT
  mode: NULLABLE
- name: p60
  type: FLOAT
  mode: NULLABLE
- name: p70
  type: FLOAT
  mode: NULLABLE
- name: p80
  type: FLOAT
  mode: NULLABLE
- name: p90
  type: FLOAT
  mode: NULLABLE
