fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: arch
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: default_search
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: osversion
  type: STRING
  mode: NULLABLE
- name: country_name
  type: STRING
  mode: NULLABLE
