fields:
- name: date
  type: DATE
  mode: NULLABLE
- name: usage
  type: STRING
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: active_days_in_week
  type: INTEGER
  mode: NULLABLE
- name: id_bucket
  type: INTEGER
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: attributed
  type: BOOLEAN
  mode: NULLABLE
