fields:
- name: country_code
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: vat
  type: NUMERIC
  mode: NULLABLE
- name: effective_date
  type: DATE
  mode: NULLABLE
