fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: addon_id
  type: STRING
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: dau_by_addon_version
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: dau_by_app_version
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: dau_by_fenix_build
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: dau_by_locale
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: dau_by_country
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: dau_by_app_os
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
