fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: date_last_seen
  type: DATE
  mode: NULLABLE
- name: date_last_seen_in_tier1_country
  type: DATE
  mode: NULLABLE
- name: user_id
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
