fields:
- name: submission_date_s3
  type: DATE
  mode: NULLABLE
- name: id
  type: STRING
  mode: NULLABLE
- name: creation_date
  type: STRING
  mode: NULLABLE
- name: application
  type: RECORD
  mode: NULLABLE
  fields:
  - name: architecture
    type: STRING
    mode: NULLABLE
  - name: build_id
    type: STRING
    mode: NULLABLE
  - name: channel
    type: STRING
    mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: platform_version
    type: STRING
    mode: NULLABLE
  - name: version
    type: STRING
    mode: NULLABLE
  - name: display_version
    type: STRING
    mode: NULLABLE
  - name: vendor
    type: STRING
    mode: NULLABLE
  - name: xpcom_abi
    type: STRING
    mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: version
  type: FLOAT
  mode: NULLABLE
- name: payload
  type: RECORD
  mode: NULLABLE
  fields:
  - name: last_version
    type: STRING
    mode: NULLABLE
  - name: last_build_id
    type: STRING
    mode: NULLABLE
  - name: has_sync
    type: BOOLEAN
    mode: NULLABLE
  - name: has_binary
    type: BOOLEAN
    mode: NULLABLE
  - name: button
    type: INTEGER
    mode: NULLABLE
