fields:
- name: platforms
  type: STRING
  mode: REPEATED
- name: country
  type: STRING
  mode: NULLABLE
- name: region
  type: STRING
  mode: NULLABLE
- name: region_subdivision
  type: STRING
  mode: NULLABLE
- name: waitlist_date
  type: DATE
  mode: NULLABLE
- name: joined_date
  type: DATE
  mode: NULLABLE
