fields:
- name: date
  type: DATE
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: country_code
  type: STRING
  mode: NULLABLE
- name: country_name
  type: STRING
  mode: NULLABLE
- name: region_name
  type: STRING
  mode: NULLABLE
- name: subregion_name
  type: STRING
  mode: NULLABLE
- name: install_count
  type: INTEGER
  mode: NULLABLE
- name: uninstall_count
  type: INTEGER
  mode: NULLABLE
- name: update_count
  type: INTEGER
  mode: NULLABLE
