fields:
- name: active_at
  type: DATE
  mode: NULLABLE
  description: Calendar week represented by this row
- name: user_count
  type: INTEGER
  mode: NULLABLE
  description: Number of Pocket twice weekly active users on this date
- name: yearly_cumulative_user_count
  type: INTEGER
  mode: NULLABLE
  description: Cumulative TWAU for the year up to this active_at date
