fields:
- name: change_date
  type: DATE
  mode: NULLABLE
  description: Date of change to the data in the table.
- name: project_id
  type: STRING
  mode: NULLABLE
  description: The ID of the project that contains the dataset
- name: dataset_id
  type: STRING
  mode: NULLABLE
  description: The name of the dataset that contains the table
- name: table_id
  type: STRING
  mode: NULLABLE
  description: The name of the table
- name: deleted
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates whether or not the table is deleted
- name: creation_date
  type: DATE
  mode: NULLABLE
  description: The table's creation date
- name: change_count
  type: INTEGER
  mode: NULLABLE
  description: The total number of changes to a table in one day
- name: avg_total_rows
  type: FLOAT
  mode: NULLABLE
  description: Average total number of rows in the table
- name: avg_total_partitions
  type: FLOAT
  mode: NULLABLE
  description: Average total number of partitions in the table
- name: avg_total_logical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average total number of uncompressed bytes in the table
- name: avg_active_logical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average number of uncompressed bytes less than 90 days old
- name: avg_long_term_logical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average number of uncompressed bytes more than 90 days old
- name: avg_total_physical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average total number of compressed  bytes used for storage
- name: avg_active_physical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average number of compressed bytes less than 90 days old
- name: avg_long_term_physical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average number of compressed bytes more than 90 days old
- name: avg_time_travel_physical_bytes
  type: FLOAT
  mode: NULLABLE
  description: Average number of compressed bytes for deleted or changed data
