fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: glean_client_id
  type: STRING
  mode: NULLABLE
- name: legacy_telemetry_client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: event_timestamp
  type: INTEGER
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: event_name
  type: STRING
  mode: NULLABLE
- name: session_action_type
  type: STRING
  mode: NULLABLE
- name: engaged_result_type
  type: STRING
  mode: NULLABLE
- name: product_engaged_result_type
  type: STRING
  mode: NULLABLE
- name: annoyance_signal_type
  type: STRING
  mode: NULLABLE
- name: first_result_type
  type: STRING
  mode: NULLABLE
- name: product_first_result_type
  type: STRING
  mode: NULLABLE
- name: num_chars_typed
  type: INTEGER
  mode: NULLABLE
- name: num_total_results
  type: INTEGER
  mode: NULLABLE
- name: is_terminal
  type: BOOLEAN
  mode: NULLABLE
- name: num_default_partner_search_suggestion_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_search_engine_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_trending_suggestion_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_history_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_open_tab_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_bookmark_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_admarketplace_sponsored_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_navigational_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_add_on_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_wikipedia_enhanced_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_wikipedia_dynamic_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_weather_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_quick_action_impressions
  type: INTEGER
  mode: NULLABLE
- name: num_pocket_collection_impressions
  type: INTEGER
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
