fields:
- name: date
  type: DATE
  mode: NULLABLE
- name: campaign_name
  type: STRING
  mode: NULLABLE
- name: campaign_id
  type: INTEGER
  mode: NULLABLE
- name: installs
  type: FLOAT
  mode: NULLABLE
- name: conversions
  type: FLOAT
  mode: NULLABLE
