fields:
- name: date
  type: DATE
  mode: NULLABLE
  description: date of the report and field that the table is partitioned by
- name: app
  type: STRING
  mode: NULLABLE
  description: name of the application such as Firefox iOS and Android, pocket
- name: network
  type: STRING
  mode: NULLABLE
- name: network_token
  type: STRING
  mode: NULLABLE
- name: campaign
  type: STRING
  mode: NULLABLE
- name: campaign_token
  type: STRING
  mode: NULLABLE
- name: adgroup
  type: STRING
  mode: NULLABLE
- name: adgroup_token
  type: STRING
  mode: NULLABLE
- name: creative
  type: STRING
  mode: NULLABLE
- name: creative_token
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: clicks
  type: INTEGER
  mode: NULLABLE
- name: installs
  type: INTEGER
  mode: NULLABLE
- name: limit_ad_tracking_install_rate
  type: FLOAT
  mode: NULLABLE
- name: click_conversion_rate
  type: FLOAT
  mode: NULLABLE
- name: impression_conversion_rate
  type: FLOAT
  mode: NULLABLE
- name: sessions
  type: INTEGER
  mode: NULLABLE
- name: daus
  type: INTEGER
  mode: NULLABLE
- name: waus
  type: INTEGER
  mode: NULLABLE
- name: maus
  type: INTEGER
  mode: NULLABLE
