fields:
- name: end_time
  type: TIMESTAMP
  mode: NULLABLE
- name: job_id
  type: STRING
  mode: NULLABLE
- name: project_id
  type: STRING
  mode: NULLABLE
- name: dataset_id
  type: STRING
  mode: NULLABLE
- name: table_id
  type: STRING
  mode: NULLABLE
- name: partition_id
  type: STRING
  mode: NULLABLE
- name: deleted_row_count
  type: INTEGER
  mode: NULLABLE
