fields:
- name: submission_minute
  type: TIMESTAMP
  mode: NULLABLE
- name: n
  type: INTEGER
  mode: NULLABLE
- name: n_release
  type: INTEGER
  mode: NULLABLE
- name: n_beta
  type: INTEGER
  mode: NULLABLE
- name: n_nightly
  type: INTEGER
  mode: NULLABLE
- name: n_merino
  type: INTEGER
  mode: NULLABLE
- name: n_merino_release
  type: INTEGER
  mode: NULLABLE
- name: n_merino_beta
  type: INTEGER
  mode: NULLABLE
- name: n_merino_nightly
  type: INTEGER
  mode: NULLABLE
