fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: events
  type: STRING
  mode: NULLABLE
- name: build_id
  type: STRING
  mode: NULLABLE
- name: build_architecture
  type: STRING
  mode: NULLABLE
- name: profile_creation_date
  type: FLOAT
  mode: NULLABLE
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
- name: attribution_source
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: attribution_ua
  type: STRING
  mode: NULLABLE
- name: display_version
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: subdivision1
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
