fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when data was captured
- name: creation_date
  type: DATE
  mode: NULLABLE
  description: The table's creation date
- name: project_id
  type: STRING
  mode: NULLABLE
  description: The ID of the project that contains the dataset
- name: dataset_id
  type: STRING
  mode: NULLABLE
  description: The name of the dataset that contains the table or view
- name: table_id
  type: STRING
  mode: NULLABLE
  description: The name of the table or view
- name: table_type
  type: STRING
  mode: NULLABLE
  description: The table type
- name: last_modified_date
  type: DATE
  mode: NULLABLE
  description: The table's last modified date
- name: owners
  type: STRING
  mode: REPEATED
  description: The owner of the table listed in metadata yaml file
- name: last_used_date
  type: DATE
  mode: NULLABLE
  description: The date when the tables was last queried
