fields:
- name: timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: event
  type: STRING
  mode: NULLABLE
- name: flow_id
  type: STRING
  mode: NULLABLE
- name: entrypoint
  type: STRING
  mode: NULLABLE
- name: service
  type: STRING
  mode: NULLABLE
- name: useragent
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: utm_source
  type: STRING
  mode: NULLABLE
- name: utm_campaign
  type: STRING
  mode: NULLABLE
- name: utm_content
  type: STRING
  mode: NULLABLE
- name: utm_medium
  type: STRING
  mode: NULLABLE
- name: utm_term
  type: STRING
  mode: NULLABLE
- name: device_id
  type: STRING
  mode: NULLABLE
