fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: user_id
  type: INTEGER
  mode: NULLABLE
- name: created_at
  type: TIMESTAMP
  mode: NULLABLE
- name: updated_at
  type: TIMESTAMP
  mode: NULLABLE
- name: platform
  type: STRING
  mode: NULLABLE
- name: useragent
  type: STRING
  mode: NULLABLE
