fields:
- name: cohort_start_month
  type: DATE
  mode: NULLABLE
  description: first day of the month when cohort starts being recorded
- name: period_length
  type: STRING
  mode: NULLABLE
  description: length of period - in this table period is set to month
- name: period
  type: INTEGER
  mode: NULLABLE
  description: period number - number of period(months) between cohort start month
    and date data is recorded
- name: app
  type: STRING
  mode: NULLABLE
  description: application name ex. Firefox iOS and Android, pocket
- name: network
  type: STRING
  mode: NULLABLE
- name: network_token
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: cohort_size
  type: INTEGER
  mode: NULLABLE
- name: retained_users
  type: INTEGER
  mode: NULLABLE
- name: retention_rate
  type: FLOAT
  mode: NULLABLE
- name: time_spent_per_user
  type: INTEGER
  mode: NULLABLE
- name: time_spent_per_session
  type: INTEGER
  mode: NULLABLE
- name: time_spent
  type: INTEGER
  mode: NULLABLE
- name: sessions_per_user
  type: FLOAT
  mode: NULLABLE
- name: sessions
  type: INTEGER
  mode: NULLABLE
- name: date
  type: DATE
  mode: NULLABLE
