fields:
- name: normalized_app_id
  mode: NULLABLE
  type: STRING
  description: App ID of the channel data was received from
- name: normalized_channel
  mode: NULLABLE
  type: STRING
  description: Normalized channel name
- name: additional_properties
  type: STRING
  mode: NULLABLE
- name: client_info
  type: RECORD
  mode: NULLABLE
  fields:
  - name: android_sdk_version
    type: STRING
    mode: NULLABLE
  - name: app_build
    type: STRING
    mode: NULLABLE
  - name: app_channel
    type: STRING
    mode: NULLABLE
  - name: app_display_version
    type: STRING
    mode: NULLABLE
  - name: architecture
    type: STRING
    mode: NULLABLE
  - name: client_id
    type: STRING
    mode: NULLABLE
  - name: device_manufacturer
    type: STRING
    mode: NULLABLE
  - name: device_model
    type: STRING
    mode: NULLABLE
  - name: first_run_date
    type: STRING
    mode: NULLABLE
  - name: locale
    type: STRING
    mode: NULLABLE
  - name: os
    type: STRING
    mode: NULLABLE
  - name: os_version
    type: STRING
    mode: NULLABLE
  - name: telemetry_sdk_build
    type: STRING
    mode: NULLABLE
  - name: build_date
    type: STRING
    mode: NULLABLE
  - name: windows_build_number
    type: INTEGER
    mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: events
  type: RECORD
  mode: REPEATED
  fields:
  - name: category
    type: STRING
    mode: NULLABLE
  - name: extra
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: STRING
      mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: geo
    type: RECORD
    mode: NULLABLE
    fields:
    - name: city
      type: STRING
      mode: NULLABLE
    - name: country
      type: STRING
      mode: NULLABLE
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: subdivision1
      type: STRING
      mode: NULLABLE
    - name: subdivision2
      type: STRING
      mode: NULLABLE
  - name: header
    type: RECORD
    mode: NULLABLE
    fields:
    - name: date
      type: STRING
      mode: NULLABLE
    - name: dnt
      type: STRING
      mode: NULLABLE
    - name: x_debug_id
      type: STRING
      mode: NULLABLE
    - name: x_pingsender_version
      type: STRING
      mode: NULLABLE
    - name: x_source_tags
      type: STRING
      mode: NULLABLE
    - name: x_telemetry_agent
      type: STRING
      mode: NULLABLE
    - name: x_foxsec_ip_reputation
      type: STRING
      mode: NULLABLE
    - name: x_lb_tags
      type: STRING
      mode: NULLABLE
    - name: parsed_date
      type: TIMESTAMP
      mode: NULLABLE
    - name: parsed_x_source_tags
      type: STRING
      mode: REPEATED
    - name: parsed_x_lb_tags
      type: RECORD
      mode: NULLABLE
      fields:
      - name: tls_version
        type: STRING
        mode: NULLABLE
      - name: tls_cipher_hex
        type: STRING
        mode: NULLABLE
  - name: isp
    type: RECORD
    mode: NULLABLE
    fields:
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: name
      type: STRING
      mode: NULLABLE
    - name: organization
      type: STRING
      mode: NULLABLE
  - name: user_agent
    type: RECORD
    mode: NULLABLE
    fields:
    - name: browser
      type: STRING
      mode: NULLABLE
    - name: os
      type: STRING
      mode: NULLABLE
    - name: version
      type: STRING
      mode: NULLABLE
- name: metrics
  type: RECORD
  mode: NULLABLE
  fields:
  - name: boolean
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_error_preinit_tasks_timeout
      type: BOOLEAN
      mode: NULLABLE
    - name: mozilla_products_has_firefox_installed
      type: BOOLEAN
      mode: NULLABLE
    - name: tracking_protection_has_advertising_blocked
      type: BOOLEAN
      mode: NULLABLE
    - name: tracking_protection_has_analytics_blocked
      type: BOOLEAN
      mode: NULLABLE
    - name: tracking_protection_has_content_blocked
      type: BOOLEAN
      mode: NULLABLE
    - name: tracking_protection_has_ever_changed_etp
      type: BOOLEAN
      mode: NULLABLE
    - name: tracking_protection_has_social_blocked
      type: BOOLEAN
      mode: NULLABLE
  - name: counter
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_error_preinit_tasks_overflow
      type: INTEGER
      mode: NULLABLE
    - name: glean_upload_deleted_pings_after_quota_hit
      type: INTEGER
      mode: NULLABLE
    - name: glean_upload_pending_pings
      type: INTEGER
      mode: NULLABLE
    - name: glean_validation_foreground_count
      type: INTEGER
      mode: NULLABLE
    - name: glean_error_io
      type: INTEGER
      mode: NULLABLE
    - name: glean_time_invalid_timezone_offset
      type: INTEGER
      mode: NULLABLE
    - name: settings_screen_autocomplete_domain_added
      type: INTEGER
      mode: NULLABLE
    - name: shortcuts_shortcut_added_counter
      type: INTEGER
      mode: NULLABLE
    - name: shortcuts_shortcut_opened_counter
      type: INTEGER
      mode: NULLABLE
    - name: tracking_protection_toolbar_shield_clicked
      type: INTEGER
      mode: NULLABLE
    - name: browser_total_uri_count
      type: INTEGER
      mode: NULLABLE
    - name: settings_screen_set_as_default_browser_pressed
      type: INTEGER
      mode: NULLABLE
    - name: app_opened_as_default_browser
      type: INTEGER
      mode: NULLABLE
    - name: default_browser_onboarding_dismiss_pressed
      type: INTEGER
      mode: NULLABLE
    - name: default_browser_onboarding_go_to_settings_pressed
      type: INTEGER
      mode: NULLABLE
    - name: browser_pdf_viewer_used
      type: INTEGER
      mode: NULLABLE
    - name: glean_upload_in_flight_pings_dropped
      type: INTEGER
      mode: NULLABLE
    - name: glean_upload_missing_send_ids
      type: INTEGER
      mode: NULLABLE
  - name: labeled_counter
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_error_invalid_label
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_overflow
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_state
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_value
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_upload_ping_upload_failure
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_validation_pings_submitted
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: shortcuts_shortcut_removed_counter
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: browser_search_ad_clicks
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: browser_search_with_ads
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: browser_search_search_count
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: browser_search_in_content
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
  - name: memory_distribution
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_database_size
      type: RECORD
      mode: NULLABLE
      fields:
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
    - name: glean_upload_discarded_exceeding_pings_size
      type: RECORD
      mode: NULLABLE
      fields:
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
    - name: glean_upload_pending_pings_directory_size
      type: RECORD
      mode: NULLABLE
      fields:
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
  - name: string
    type: RECORD
    mode: NULLABLE
    fields:
    - name: ping_reason
      type: STRING
      mode: NULLABLE
    - name: preferences_user_theme
      type: STRING
      mode: NULLABLE
    - name: search_default_engine
      type: STRING
      mode: NULLABLE
    - name: app_keyboard_type
      type: STRING
      mode: NULLABLE
    - name: glean_client_annotation_experimentation_id
      type: STRING
      mode: NULLABLE
  - name: datetime
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_validation_first_run_hour
      type: TIMESTAMP
      mode: NULLABLE
    - name: raw_glean_validation_first_run_hour
      type: STRING
      mode: NULLABLE
  - name: quantity
    type: RECORD
    mode: NULLABLE
    fields:
    - name: shortcuts_shortcuts_on_home_number
      type: INTEGER
      mode: NULLABLE
  - name: timing_distribution
    type: RECORD
    mode: NULLABLE
    fields:
    - name: nimbus_health_apply_pending_experiments_time
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
    - name: nimbus_health_fetch_experiments_time
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
    - name: glean_upload_send_failure
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
    - name: glean_upload_send_success
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
    - name: glean_validation_shutdown_wait
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
    - name: glean_validation_shutdown_dispatcher_wait
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bucket_count
        type: INTEGER
        mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
      - name: histogram_type
        type: STRING
        mode: NULLABLE
      - name: overflow
        type: INTEGER
        mode: NULLABLE
      - name: range
        type: FLOAT
        mode: REPEATED
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: underflow
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
- name: normalized_app_name
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: ping_info
  type: RECORD
  mode: NULLABLE
  fields:
  - name: end_time
    type: STRING
    mode: NULLABLE
  - name: experiments
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: RECORD
      mode: NULLABLE
      fields:
      - name: branch
        type: STRING
        mode: NULLABLE
      - name: extra
        type: RECORD
        mode: NULLABLE
        fields:
        - name: type
          type: STRING
          mode: NULLABLE
        - name: enrollment_id
          type: STRING
          mode: NULLABLE
  - name: ping_type
    type: STRING
    mode: NULLABLE
  - name: reason
    type: STRING
    mode: NULLABLE
  - name: seq
    type: INTEGER
    mode: NULLABLE
  - name: start_time
    type: STRING
    mode: NULLABLE
  - name: parsed_start_time
    type: TIMESTAMP
    mode: NULLABLE
  - name: parsed_end_time
    type: TIMESTAMP
    mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
