fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: cohort_date
  type: DATE
  mode: NULLABLE
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: activations_count
  type: INTEGER
  mode: NULLABLE
- name: active_day_count
  type: INTEGER
  mode: NULLABLE
- name: searches
  type: INTEGER
  mode: NULLABLE
- name: searches_with_ads
  type: INTEGER
  mode: NULLABLE
- name: ad_clicks
  type: INTEGER
  mode: NULLABLE
- name: first_reported_country
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: is_new_install
  type: BOOLEAN
  mode: NULLABLE
- name: is_new_profile
  type: BOOLEAN
  mode: NULLABLE
- name: is_activated
  type: BOOLEAN
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: sent_baseline_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: sent_metrics_search_data
    type: BOOLEAN
    mode: NULLABLE
  - name: activated_on_this_day
    type: BOOLEAN
    mode: NULLABLE
- name: firefox_android_clients_metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: reported_first_session_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_metrics_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_baseline_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: min_first_session_ping_submission_date
    type: DATE
    mode: NULLABLE
  - name: min_first_session_ping_run_date
    type: DATE
    mode: NULLABLE
  - name: min_metrics_ping_submission_date
    type: DATE
    mode: NULLABLE
  - name: adjust_network__source_ping
    type: STRING
    mode: NULLABLE
  - name: install_source__source_ping
    type: STRING
    mode: NULLABLE
  - name: adjust_network__source_ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: install_source__source_ping_datetime
    type: DATETIME
    mode: NULLABLE
