fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: 'Corresponds to the submission_date of the record

    used from fxa_users_services_daily_v2.


    IMPORTANT:

    submission_date and first_service_flow_timestamp

    will not always have the same date (should at most be 1

    day difference). When filtering for users that we first

    saw on x day should be done using

    DATE(first_service_flow_timestamp) = "DAY".

    '
- name: user_id
  type: STRING
  mode: NULLABLE
  description: '36-char long hash randomly assigned when the account

    is created.

    '
- name: service
  type: STRING
  mode: NULLABLE
  description: 'The service identifier. For Sync it may be empty or sync.

    For OAuth reliers it is their hex client id.

    Example: sync

    '
- name: did_register
  type: BOOLEAN
  mode: NULLABLE
  description: 'Set to True if the user submitted

    the event_type of `fxa_reg - complete`

    event on the specific submission_date.

    '
- name: first_service_os_name
  type: STRING
  mode: NULLABLE
  description: 'Name of the operating system the device was using.

    E.g. Android

    '
- name: first_service_os_version
  type: STRING
  mode: NULLABLE
  description: 'Version of the OS the device was using.

    '
- name: first_service_app_version
  type: STRING
  mode: NULLABLE
  description: 'Mozilla app version,

    follows format: major.minor.patch (e.g. 99.3.3).

    '
- name: first_service_country
  type: STRING
  mode: NULLABLE
  description: '2 char string representing the country where the device was located.

    '
- name: first_service_language
  type: STRING
  mode: NULLABLE
  description: 'Language settings used by the device.

    '
- name: first_service_ua_version
  type: STRING
  mode: NULLABLE
  description: 'The user''s browser version.

    '
- name: first_service_ua_browser
  type: STRING
  mode: NULLABLE
  description: 'The user''s web browser, e.g. ''Firefox'' or ''Chrome''.

    '
- name: first_service_flow_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: first_service_flow_entrypoint
  type: STRING
  mode: NULLABLE
- name: first_service_flow_utm_term
  type: STRING
  mode: NULLABLE
- name: first_service_flow_utm_medium
  type: STRING
  mode: NULLABLE
- name: first_service_flow_utm_source
  type: STRING
  mode: NULLABLE
- name: first_service_flow_utm_campaign
  type: STRING
  mode: NULLABLE
- name: first_service_flow_utm_content
  type: STRING
  mode: NULLABLE
- name: first_service_flow_id
  type: STRING
  mode: NULLABLE
