fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: id_bucket
  type: INTEGER
  mode: NULLABLE
- name: product
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: campaign
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
- name: country_name
  type: STRING
  mode: NULLABLE
