fields:
- name: normalized_app_id
  mode: NULLABLE
  type: STRING
  description: App ID of the channel data was received from
- name: normalized_channel
  mode: NULLABLE
  type: STRING
  description: Normalized channel name
- name: additional_properties
  type: STRING
  mode: NULLABLE
- name: client_info
  type: RECORD
  mode: NULLABLE
  fields:
  - name: android_sdk_version
    type: STRING
    mode: NULLABLE
  - name: app_build
    type: STRING
    mode: NULLABLE
  - name: app_channel
    type: STRING
    mode: NULLABLE
  - name: app_display_version
    type: STRING
    mode: NULLABLE
  - name: architecture
    type: STRING
    mode: NULLABLE
  - name: client_id
    type: STRING
    mode: NULLABLE
  - name: device_manufacturer
    type: STRING
    mode: NULLABLE
  - name: device_model
    type: STRING
    mode: NULLABLE
  - name: first_run_date
    type: STRING
    mode: NULLABLE
  - name: locale
    type: STRING
    mode: NULLABLE
  - name: os
    type: STRING
    mode: NULLABLE
  - name: os_version
    type: STRING
    mode: NULLABLE
  - name: telemetry_sdk_build
    type: STRING
    mode: NULLABLE
  - name: build_date
    type: STRING
    mode: NULLABLE
  - name: windows_build_number
    type: INTEGER
    mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: events
  type: RECORD
  mode: REPEATED
  fields:
  - name: category
    type: STRING
    mode: NULLABLE
  - name: extra
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: STRING
      mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: geo
    type: RECORD
    mode: NULLABLE
    fields:
    - name: city
      type: STRING
      mode: NULLABLE
    - name: country
      type: STRING
      mode: NULLABLE
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: subdivision1
      type: STRING
      mode: NULLABLE
    - name: subdivision2
      type: STRING
      mode: NULLABLE
  - name: header
    type: RECORD
    mode: NULLABLE
    fields:
    - name: date
      type: STRING
      mode: NULLABLE
    - name: dnt
      type: STRING
      mode: NULLABLE
    - name: x_debug_id
      type: STRING
      mode: NULLABLE
    - name: x_pingsender_version
      type: STRING
      mode: NULLABLE
    - name: x_source_tags
      type: STRING
      mode: NULLABLE
    - name: x_telemetry_agent
      type: STRING
      mode: NULLABLE
    - name: x_foxsec_ip_reputation
      type: STRING
      mode: NULLABLE
    - name: x_lb_tags
      type: STRING
      mode: NULLABLE
    - name: parsed_date
      type: TIMESTAMP
      mode: NULLABLE
    - name: parsed_x_source_tags
      type: STRING
      mode: REPEATED
    - name: parsed_x_lb_tags
      type: RECORD
      mode: NULLABLE
      fields:
      - name: tls_version
        type: STRING
        mode: NULLABLE
      - name: tls_cipher_hex
        type: STRING
        mode: NULLABLE
  - name: isp
    type: RECORD
    mode: NULLABLE
    fields:
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: name
      type: STRING
      mode: NULLABLE
    - name: organization
      type: STRING
      mode: NULLABLE
  - name: user_agent
    type: RECORD
    mode: NULLABLE
    fields:
    - name: browser
      type: STRING
      mode: NULLABLE
    - name: os
      type: STRING
      mode: NULLABLE
    - name: version
      type: STRING
      mode: NULLABLE
- name: metrics
  type: RECORD
  mode: NULLABLE
  fields:
  - name: boolean
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_success
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_artifact
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_ccache
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_clobber
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_debug
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_icecream
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_opt
      type: BOOLEAN
      mode: NULLABLE
    - name: mozbuild_sccache
      type: BOOLEAN
      mode: NULLABLE
    - name: mach_system_ssh_connection
      type: BOOLEAN
      mode: NULLABLE
    - name: mach_system_vscode_terminal
      type: BOOLEAN
      mode: NULLABLE
    - name: mach_system_vscode_running
      type: BOOLEAN
      mode: NULLABLE
  - name: counter
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_system_logical_cores
      type: INTEGER
      mode: NULLABLE
    - name: mach_system_physical_cores
      type: INTEGER
      mode: NULLABLE
  - name: labeled_counter
    type: RECORD
    mode: NULLABLE
    fields:
    - name: glean_error_invalid_label
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_overflow
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_state
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
    - name: glean_error_invalid_value
      type: RECORD
      mode: REPEATED
      fields:
      - name: key
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
  - name: memory_distribution
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_system_memory
      type: RECORD
      mode: NULLABLE
      fields:
      - name: sum
        type: INTEGER
        mode: NULLABLE
      - name: values
        type: RECORD
        mode: REPEATED
        fields:
        - name: key
          type: STRING
          mode: NULLABLE
        - name: value
          type: INTEGER
          mode: NULLABLE
      - name: count
        type: INTEGER
        mode: NULLABLE
  - name: string
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_command
      type: STRING
      mode: NULLABLE
    - name: mach_system_cpu_brand
      type: STRING
      mode: NULLABLE
    - name: mozbuild_compiler
      type: STRING
      mode: NULLABLE
    - name: mach_system_distro
      type: STRING
      mode: NULLABLE
    - name: mach_system_distro_version
      type: STRING
      mode: NULLABLE
    - name: glean_client_annotation_experimentation_id
      type: STRING
      mode: NULLABLE
  - name: string_list
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_argv
      type: STRING
      mode: REPEATED
  - name: timespan
    type: RECORD
    mode: NULLABLE
    fields:
    - name: mach_duration
      type: RECORD
      mode: NULLABLE
      fields:
      - name: time_unit
        type: STRING
        mode: NULLABLE
      - name: value
        type: INTEGER
        mode: NULLABLE
- name: normalized_app_name
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: ping_info
  type: RECORD
  mode: NULLABLE
  fields:
  - name: end_time
    type: STRING
    mode: NULLABLE
  - name: experiments
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: RECORD
      mode: NULLABLE
      fields:
      - name: branch
        type: STRING
        mode: NULLABLE
      - name: extra
        type: RECORD
        mode: NULLABLE
        fields:
        - name: type
          type: STRING
          mode: NULLABLE
        - name: enrollment_id
          type: STRING
          mode: NULLABLE
  - name: ping_type
    type: STRING
    mode: NULLABLE
  - name: reason
    type: STRING
    mode: NULLABLE
  - name: seq
    type: INTEGER
    mode: NULLABLE
  - name: start_time
    type: STRING
    mode: NULLABLE
  - name: parsed_start_time
    type: TIMESTAMP
    mode: NULLABLE
  - name: parsed_end_time
    type: TIMESTAMP
    mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
