fields:
- name: days_since_seen
  type: INTEGER
  mode: NULLABLE
- name: days_since_seen_in_tier1_country
  type: INTEGER
  mode: NULLABLE
- name: days_since_registered
  type: INTEGER
  mode: NULLABLE
- name: days_since_seen_no_monitor
  type: INTEGER
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: 'Corresponds to ETL processing date.

    Also, used for partitioning the table.

    '
- name: days_seen_bits
  type: INTEGER
  mode: NULLABLE
  description: 'No. of days since the user had activity event.

    '
- name: days_seen_in_tier1_country_bits
  type: INTEGER
  mode: NULLABLE
  description: 'No. of days since seen_in_tier1_country was last True.

    '
- name: days_registered_bits
  type: INTEGER
  mode: NULLABLE
  description: 'No. of days since registration event.

    '
- name: user_id
  type: STRING
  mode: NULLABLE
  description: 'A 36 char long hash value representing

    User ID (registered user).

    '
- name: country
  type: STRING
  mode: NULLABLE
  description: 'User''s country where activity took place.

    See: UDF mozdata.stats.mode_last for more

    info on how the function operates.

    '
- name: language
  type: STRING
  mode: NULLABLE
  description: 'Most recently used language.

    '
- name: app_version
  type: STRING
  mode: NULLABLE
  description: 'Mozilla app version most recently used,

    follows format: major.minor.patch (e.g. 99.3.3).

    '
- name: os_name
  type: STRING
  mode: NULLABLE
  description: 'OS on which the app was most recently running.

    For example: Android.

    '
- name: os_version
  type: STRING
  mode: NULLABLE
  description: 'Version of the OS the device was most recently using.

    '
- name: days_seen_no_monitor_bits
  type: INTEGER
  mode: NULLABLE
  description: 'No. of days since monitor flag was last True.

    '
