fields:
- name: flow_id
  type: STRING
  mode: NULLABLE
  description: 'The flow associated with the first seen session.

    The flow identifier is a hash value representing

    a registration and login sessions.

    '
- name: user_id
  type: STRING
  mode: NULLABLE
  description: 'Unique identifier of a registered user.

    '
- name: service
  type: STRING
  mode: NULLABLE
  description: 'The service identifier. For Sync it may be empty or sync.

    For OAuth reliers it is their hex client id.

    A service corresponds to a specific application,

    for example: "sync".

    '
- name: device_id
  type: STRING
  mode: NULLABLE
  description: 'This DOES NOT correspond to a physical device! Everytime a user logs
    out and back

    in will have a different value for device_id. This should be treated more like

    a session identified (in our case, session does not expire).

    There are two ways in which device_id field value gets populated/generated:

    1. If the current flow session does not have a device_id associated with it we
    set

    it to the device_id/deviceId value found inside urlParams object.

    2. If during the above process we find urlParams object to not have this attribute
    set,

    then we use uuid.v4() to generate a new unique value and assign it to deviceId
    flow session.

    _devide_id generation: https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/app/scripts/models/flow.js#L61-L69_

    '
- name: os_name
  type: STRING
  mode: NULLABLE
  description: 'Name of the operating system the device was using.

    E.g. Android

    '
- name: country
  type: STRING
  mode: NULLABLE
  description: '2 char string representing the country where the device was located.

    '
- name: language
  type: STRING
  mode: NULLABLE
  description: 'Language settings used by the device.

    '
- name: entrypoint
  type: STRING
  mode: NULLABLE
  description: 'The entrypoint of the flow session.

    How a user begins their registration or login flow.

    Typically a UI touchpoint like "preferences".

    '
- name: first_seen_date
  type: TIMESTAMP
  mode: NULLABLE
  description: 'Datetime value when the user, service, device_id

    was seen for the first time.

    '
- name: utm_term
  type: STRING
  mode: NULLABLE
  description: 'Marketing campaign search term

    for the flow session.

    Not stored if the DNT request header was 1.

    '
- name: utm_medium
  type: STRING
  mode: NULLABLE
  description: 'Marketing campaign medium for the flow session.

    Not stored if the DNT request header was 1.

    '
- name: utm_source
  type: STRING
  mode: NULLABLE
  description: 'Marketing campaign source for

    the flow session.

    Not stored if the DNT request header was 1.

    '
- name: utm_campaign
  type: STRING
  mode: NULLABLE
  description: 'Marketing campaign identifier

    for the flow session.

    Not stored if the DNT request header was 1.

    '
- name: utm_content
  type: STRING
  mode: NULLABLE
  description: 'Marketing campaign content identifier

    for the flow session.

    Not stored if the DNT request header was 1.

    '
- name: ua_version
  type: STRING
  mode: NULLABLE
  description: 'The user''s browser version.

    '
- name: ua_browser
  type: STRING
  mode: NULLABLE
  description: 'The user''s web browser, e.g. ''Firefox'' or ''Chrome''.

    '
- name: event_type
  type: STRING
  mode: NULLABLE
  description: 'Type of the FxA event recorded.

    `fxa_login - complete'' and ''fxa_reg - complete`

    are the events used to create this table.

    '
