fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: recency
  type: INTEGER
  mode: NULLABLE
- name: frequency
  type: INTEGER
  mode: NULLABLE
- name: num_opportunities
  type: INTEGER
  mode: NULLABLE
- name: max_day
  type: STRING
  mode: NULLABLE
- name: min_day
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: prob_active
  type: FLOAT
  mode: NULLABLE
- name: e_total_days_in_next_7_days
  type: FLOAT
  mode: NULLABLE
- name: e_total_days_in_next_14_days
  type: FLOAT
  mode: NULLABLE
- name: e_total_days_in_next_21_days
  type: FLOAT
  mode: NULLABLE
- name: e_total_days_in_next_28_days
  type: FLOAT
  mode: NULLABLE
- name: prob_daily_usage
  type: FLOAT
  mode: NULLABLE
- name: prob_daily_leave
  type: FLOAT
  mode: NULLABLE
- name: prob_mau
  type: FLOAT
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
