fields:
- name: id
  type: INTEGER
  mode: NULLABLE
  description: Pool id
- name: pool
  type: STRING
  mode: NULLABLE
  description: Pool name
- name: description
  type: STRING
  mode: NULLABLE
  description: Pool description
- name: slots
  type: INTEGER
  mode: NULLABLE
  description: Number of slots available in the pool
