fields:
- name: source_project
  type: STRING
  mode: NULLABLE
  description: Project used for executing job
- name: creation_date
  type: DATE
  mode: NULLABLE
  description: Job creation date
- name: job_id
  type: STRING
  mode: NULLABLE
  description: ID of job
- name: job_type
  type: STRING
  mode: NULLABLE
  description: The type of the job
- name: state
  type: STRING
  mode: NULLABLE
  description: Running state of the job
- name: reference_project_id
  type: STRING
  mode: NULLABLE
  description: The ID of the project referenced by the job
- name: reference_dataset_id
  type: STRING
  mode: NULLABLE
  description: The ID of the dataset referenced by the job
- name: reference_table_id
  type: STRING
  mode: NULLABLE
  description: The ID of the table referenced by the job
- name: destination_project_id
  type: STRING
  mode: NULLABLE
  description: The ID of the project containing the destination table
- name: destination_dataset_id
  type: STRING
  mode: NULLABLE
  description: The ID of the dataset containing the destination table
- name: destination_table_id
  type: STRING
  mode: NULLABLE
  description: The ID of the destination table
- name: user_email
  type: STRING
  mode: NULLABLE
  description: Email address or service account of the user who ran the job
- name: username
  type: STRING
  mode: NULLABLE
  description: Email address of the user who ran the query
- name: query_id
  type: STRING
  mode: NULLABLE
  description: query id of the job
- name: task_duration
  type: INTERVAL
  mode: NULLABLE
  description: The time it took to run the job
- name: total_terabytes_processed
  type: FLOAT
  mode: NULLABLE
  description: Total terabytes processed by the job
- name: error_location
  type: STRING
  mode: NULLABLE
  description: Specifies where the error occurred, if present
- name: error_reason
  type: STRING
  mode: NULLABLE
  description: A short error code that summarizes the error
- name: error_message
  type: STRING
  mode: NULLABLE
  description: A human-readable description of the error
- name: reservation_id
  type: STRING
  mode: NULLABLE
  description: Name of the primary reservation (slots for distributing resources)
    assigned to this job.
- name: cache_hit
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the query results of this job were from a cache
